// AI Tools Comparison Database
// A comprehensive, filterable database of AI automation tools for business

export const categories = [
  { id: 'all', name: 'All Tools', icon: '🔧' },
  { id: 'lead-generation', name: 'Lead Generation', icon: '🎯' },
  { id: 'email-outreach', name: 'Email Outreach', icon: '📧' },
  { id: 'data-enrichment', name: 'Data Enrichment', icon: '📊' },
  { id: 'workflow-automation', name: 'Workflow Automation', icon: '⚡' },
  { id: 'crm', name: 'CRM', icon: '👥' },
  { id: 'ai-writing', name: 'AI Writing', icon: '✍️' },
  { id: 'sales-intelligence', name: 'Sales Intelligence', icon: '🔍' },
  { id: 'scheduling', name: 'Scheduling', icon: '📅' },
  { id: 'analytics', name: 'Analytics', icon: '📈' },
];

export const pricingTiers = [
  { id: 'all', name: 'All Prices' },
  { id: 'free', name: 'Free Tier Available' },
  { id: 'under-50', name: 'Under $50/mo' },
  { id: '50-100', name: '$50-100/mo' },
  { id: '100-plus', name: '$100+/mo' },
];

export const aiTools = [
  // Lead Generation Tools
  {
    id: 'apollo',
    name: 'Apollo.io',
    category: 'lead-generation',
    description: 'All-in-one sales intelligence and engagement platform with 275M+ contacts database.',
    pricing: '$49/mo',
    pricingTier: 'under-50',
    bestFor: 'B2B lead prospecting and email sequences',
    features: ['275M+ contact database', 'Email sequences', 'Chrome extension', 'CRM integrations'],
    integrations: ['Salesforce', 'HubSpot', 'Outreach', 'Zapier'],
    rating: 4.8,
    website: 'https://www.apollo.io',
    hasFree: true,
  },
  {
    id: 'linkedin-sales-navigator',
    name: 'LinkedIn Sales Navigator',
    category: 'lead-generation',
    description: 'Premium LinkedIn tool for finding and connecting with decision-makers.',
    pricing: '$99/mo',
    pricingTier: '50-100',
    bestFor: 'Finding decision-makers at target companies',
    features: ['Advanced search filters', 'Lead recommendations', 'InMail credits', 'CRM sync'],
    integrations: ['Salesforce', 'HubSpot', 'Microsoft Dynamics'],
    rating: 4.5,
    website: 'https://business.linkedin.com/sales-solutions',
    hasFree: false,
  },
  {
    id: 'clay',
    name: 'Clay',
    category: 'lead-generation',
    description: 'Data enrichment and outbound automation platform with 75+ data providers.',
    pricing: '$149/mo',
    pricingTier: '100-plus',
    bestFor: 'Complex lead enrichment workflows',
    features: ['75+ data providers', 'AI research agent', 'Waterfall enrichment', 'Custom formulas'],
    integrations: ['Salesforce', 'HubSpot', 'Outreach', 'Apollo'],
    rating: 4.7,
    website: 'https://www.clay.com',
    hasFree: true,
  },
  {
    id: 'zoominfo',
    name: 'ZoomInfo',
    category: 'lead-generation',
    description: 'Enterprise B2B contact database with intent data and company insights.',
    pricing: '$15,000/yr',
    pricingTier: '100-plus',
    bestFor: 'Enterprise sales teams needing verified data',
    features: ['Intent data', 'Org charts', 'Technographics', 'Website visitor tracking'],
    integrations: ['Salesforce', 'HubSpot', 'Marketo', 'Outreach'],
    rating: 4.4,
    website: 'https://www.zoominfo.com',
    hasFree: false,
  },
  {
    id: 'hunter',
    name: 'Hunter.io',
    category: 'lead-generation',
    description: 'Email finder and verifier for finding professional email addresses.',
    pricing: '$49/mo',
    pricingTier: 'under-50',
    bestFor: 'Finding and verifying business emails',
    features: ['Email finder', 'Email verifier', 'Domain search', 'Chrome extension'],
    integrations: ['HubSpot', 'Salesforce', 'Pipedrive', 'Zapier'],
    rating: 4.6,
    website: 'https://hunter.io',
    hasFree: true,
  },
  {
    id: 'snov',
    name: 'Snov.io',
    category: 'lead-generation',
    description: 'Sales automation platform with email finder, verifier, and drip campaigns.',
    pricing: '$39/mo',
    pricingTier: 'under-50',
    bestFor: 'Startups needing affordable lead gen',
    features: ['Email finder', 'Email verifier', 'Drip campaigns', 'Technology checker'],
    integrations: ['HubSpot', 'Pipedrive', 'Zapier', 'Make'],
    rating: 4.5,
    website: 'https://snov.io',
    hasFree: true,
  },
  {
    id: 'lusha',
    name: 'Lusha',
    category: 'lead-generation',
    description: 'B2B contact data platform with direct dials and email addresses.',
    pricing: '$29/mo',
    pricingTier: 'under-50',
    bestFor: 'Direct dial phone numbers',
    features: ['Direct dials', 'Email addresses', 'Chrome extension', 'Bulk enrichment'],
    integrations: ['Salesforce', 'HubSpot', 'Outreach', 'Zapier'],
    rating: 4.3,
    website: 'https://www.lusha.com',
    hasFree: true,
  },
  {
    id: 'leadiq',
    name: 'LeadIQ',
    category: 'lead-generation',
    description: 'Prospecting platform that captures lead data from anywhere on the web.',
    pricing: '$75/mo',
    pricingTier: '50-100',
    bestFor: 'Sales teams doing LinkedIn prospecting',
    features: ['One-click capture', 'Email verification', 'Salesforce sync', 'Sequence push'],
    integrations: ['Salesforce', 'HubSpot', 'Outreach', 'Salesloft'],
    rating: 4.4,
    website: 'https://leadiq.com',
    hasFree: true,
  },

  // Email Outreach Tools
  {
    id: 'instantly',
    name: 'Instantly.ai',
    category: 'email-outreach',
    description: 'Cold email platform with unlimited email accounts and warmup.',
    pricing: '$37/mo',
    pricingTier: 'under-50',
    bestFor: 'High-volume cold email campaigns',
    features: ['Unlimited email accounts', 'Email warmup', 'AI personalization', 'Deliverability dashboard'],
    integrations: ['Zapier', 'Make', 'HubSpot', 'Pipedrive'],
    rating: 4.8,
    website: 'https://instantly.ai',
    hasFree: false,
  },
  {
    id: 'smartlead',
    name: 'Smartlead',
    category: 'email-outreach',
    description: 'Cold outreach platform with unlimited mailboxes and auto-rotating.',
    pricing: '$39/mo',
    pricingTier: 'under-50',
    bestFor: 'Agencies managing multiple clients',
    features: ['Unlimited mailboxes', 'Auto-rotating', 'Unified inbox', 'White-label'],
    integrations: ['HubSpot', 'Pipedrive', 'Zapier', 'Webhooks'],
    rating: 4.7,
    website: 'https://www.smartlead.ai',
    hasFree: false,
  },
  {
    id: 'lemlist',
    name: 'Lemlist',
    category: 'email-outreach',
    description: 'Personalized cold email and LinkedIn outreach with image personalization.',
    pricing: '$59/mo',
    pricingTier: '50-100',
    bestFor: 'Personalized image/video outreach',
    features: ['Image personalization', 'LinkedIn automation', 'Email warmup', 'A/B testing'],
    integrations: ['HubSpot', 'Salesforce', 'Pipedrive', 'Zapier'],
    rating: 4.6,
    website: 'https://www.lemlist.com',
    hasFree: false,
  },
  {
    id: 'mailshake',
    name: 'Mailshake',
    category: 'email-outreach',
    description: 'Sales engagement platform for email and phone outreach.',
    pricing: '$58/mo',
    pricingTier: '50-100',
    bestFor: 'Combined email and phone outreach',
    features: ['Email sequences', 'Phone dialer', 'Social selling', 'Lead catcher'],
    integrations: ['Salesforce', 'HubSpot', 'Pipedrive', 'Zapier'],
    rating: 4.5,
    website: 'https://mailshake.com',
    hasFree: false,
  },
  {
    id: 'woodpecker',
    name: 'Woodpecker',
    category: 'email-outreach',
    description: 'Cold email tool with agency features and deliverability focus.',
    pricing: '$49/mo',
    pricingTier: 'under-50',
    bestFor: 'Agencies with multiple clients',
    features: ['A/B testing', 'Condition-based campaigns', 'Agency panel', 'Deliverability monitor'],
    integrations: ['HubSpot', 'Pipedrive', 'Salesforce', 'Zapier'],
    rating: 4.5,
    website: 'https://woodpecker.co',
    hasFree: true,
  },
  {
    id: 'reply',
    name: 'Reply.io',
    category: 'email-outreach',
    description: 'Multichannel sales engagement with AI-powered email writing.',
    pricing: '$60/mo',
    pricingTier: '50-100',
    bestFor: 'Multichannel sequences (email + LinkedIn)',
    features: ['AI email writer', 'LinkedIn automation', 'Call integration', 'Meeting scheduler'],
    integrations: ['Salesforce', 'HubSpot', 'Pipedrive', 'Copper'],
    rating: 4.6,
    website: 'https://reply.io',
    hasFree: true,
  },
  {
    id: 'outreach',
    name: 'Outreach',
    category: 'email-outreach',
    description: 'Enterprise sales execution platform with revenue intelligence.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Enterprise sales teams',
    features: ['Sequence automation', 'Revenue intelligence', 'Deal insights', 'Conversation intelligence'],
    integrations: ['Salesforce', 'Microsoft Dynamics', 'LinkedIn', 'Gong'],
    rating: 4.4,
    website: 'https://www.outreach.io',
    hasFree: false,
  },
  {
    id: 'salesloft',
    name: 'Salesloft',
    category: 'email-outreach',
    description: 'Revenue workflow platform for sales engagement and pipeline management.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Large sales organizations',
    features: ['Cadence automation', 'Conversation intelligence', 'Deals', 'Forecast'],
    integrations: ['Salesforce', 'HubSpot', 'Microsoft Dynamics', 'LinkedIn'],
    rating: 4.5,
    website: 'https://www.salesloft.com',
    hasFree: false,
  },

  // Data Enrichment Tools
  {
    id: 'clearbit',
    name: 'Clearbit',
    category: 'data-enrichment',
    description: 'B2B data enrichment API for real-time company and person data.',
    pricing: '$99/mo',
    pricingTier: '50-100',
    bestFor: 'Real-time lead enrichment in forms',
    features: ['Company data', 'Person data', 'IP reveal', 'Form shortening'],
    integrations: ['HubSpot', 'Salesforce', 'Marketo', 'Segment'],
    rating: 4.6,
    website: 'https://clearbit.com',
    hasFree: true,
  },
  {
    id: 'builtwith',
    name: 'BuiltWith',
    category: 'data-enrichment',
    description: 'Technology lookup tool that shows what websites are built with.',
    pricing: '$295/mo',
    pricingTier: '100-plus',
    bestFor: 'Tech stack prospecting',
    features: ['Technology tracking', 'Lead lists', 'Market analysis', 'Chrome extension'],
    integrations: ['Salesforce', 'HubSpot', 'API access'],
    rating: 4.4,
    website: 'https://builtwith.com',
    hasFree: true,
  },
  {
    id: 'crunchbase',
    name: 'Crunchbase',
    category: 'data-enrichment',
    description: 'Company intelligence platform with funding, acquisitions, and industry data.',
    pricing: '$29/mo',
    pricingTier: 'under-50',
    bestFor: 'Researching company funding and news',
    features: ['Company profiles', 'Funding data', 'Industry trends', 'Saved searches'],
    integrations: ['Salesforce', 'HubSpot', 'Outreach', 'API'],
    rating: 4.5,
    website: 'https://www.crunchbase.com',
    hasFree: true,
  },
  {
    id: 'phantombuster',
    name: 'PhantomBuster',
    category: 'data-enrichment',
    description: 'No-code automation for extracting data from LinkedIn, Twitter, and more.',
    pricing: '$56/mo',
    pricingTier: '50-100',
    bestFor: 'Scraping LinkedIn and social platforms',
    features: ['LinkedIn scraping', 'Auto-follow', 'Data extraction', 'Workflow chains'],
    integrations: ['Google Sheets', 'HubSpot', 'Salesforce', 'Zapier'],
    rating: 4.4,
    website: 'https://phantombuster.com',
    hasFree: true,
  },
  {
    id: 'apify',
    name: 'Apify',
    category: 'data-enrichment',
    description: 'Web scraping and automation platform with 1,500+ ready-made scrapers.',
    pricing: '$49/mo',
    pricingTier: 'under-50',
    bestFor: 'Custom web scraping at scale',
    features: ['1500+ actors', 'Proxy rotation', 'Scheduling', 'API access'],
    integrations: ['Zapier', 'Make', 'Webhooks', 'Google Sheets'],
    rating: 4.6,
    website: 'https://apify.com',
    hasFree: true,
  },
  {
    id: 'neverbounce',
    name: 'NeverBounce',
    category: 'data-enrichment',
    description: 'Email verification service to clean email lists and improve deliverability.',
    pricing: '$0.003/email',
    pricingTier: 'under-50',
    bestFor: 'Bulk email list cleaning',
    features: ['Real-time verification', 'Bulk cleaning', 'API access', 'Integrations'],
    integrations: ['Mailchimp', 'HubSpot', 'Zapier', 'API'],
    rating: 4.7,
    website: 'https://neverbounce.com',
    hasFree: true,
  },
  {
    id: 'zerobounce',
    name: 'ZeroBounce',
    category: 'data-enrichment',
    description: 'Email validation and deliverability toolkit with AI-powered scoring.',
    pricing: '$0.007/email',
    pricingTier: 'under-50',
    bestFor: 'Email validation with activity data',
    features: ['Email validation', 'Activity data', 'Abuse detection', 'Deliverability toolkit'],
    integrations: ['Mailchimp', 'HubSpot', 'Zapier', 'Salesforce'],
    rating: 4.6,
    website: 'https://www.zerobounce.net',
    hasFree: true,
  },

  // Workflow Automation Tools
  {
    id: 'make',
    name: 'Make (Integromat)',
    category: 'workflow-automation',
    description: 'Visual automation platform connecting 1,500+ apps with complex logic.',
    pricing: '$9/mo',
    pricingTier: 'under-50',
    bestFor: 'Complex multi-step automations',
    features: ['Visual builder', '1500+ apps', 'Data manipulation', 'Error handling'],
    integrations: ['Google Workspace', 'Salesforce', 'HubSpot', 'Slack'],
    rating: 4.8,
    website: 'https://www.make.com',
    hasFree: true,
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'workflow-automation',
    description: 'No-code automation platform connecting 6,000+ apps with simple triggers.',
    pricing: '$19.99/mo',
    pricingTier: 'under-50',
    bestFor: 'Simple automations and beginners',
    features: ['6000+ apps', 'Multi-step zaps', 'Paths', 'Formatter'],
    integrations: ['Gmail', 'Slack', 'Salesforce', 'HubSpot'],
    rating: 4.7,
    website: 'https://zapier.com',
    hasFree: true,
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'workflow-automation',
    description: 'Open-source workflow automation with self-hosting option and code nodes.',
    pricing: '$20/mo',
    pricingTier: 'under-50',
    bestFor: 'Developers wanting control and customization',
    features: ['Self-hostable', 'Code nodes', '400+ integrations', 'Git sync'],
    integrations: ['Most APIs', 'Databases', 'AI models', 'Custom code'],
    rating: 4.7,
    website: 'https://n8n.io',
    hasFree: true,
  },
  {
    id: 'tray',
    name: 'Tray.io',
    category: 'workflow-automation',
    description: 'Enterprise automation platform for complex business processes.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Enterprise workflow automation',
    features: ['Visual builder', 'Universal connector', 'Branching logic', 'Enterprise security'],
    integrations: ['Salesforce', 'NetSuite', 'Workday', 'ServiceNow'],
    rating: 4.5,
    website: 'https://tray.io',
    hasFree: false,
  },
  {
    id: 'workato',
    name: 'Workato',
    category: 'workflow-automation',
    description: 'Enterprise integration and automation platform with AI capabilities.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Large enterprises needing governance',
    features: ['Recipe builder', 'AI copilot', 'Workbot', 'Enterprise security'],
    integrations: ['SAP', 'Oracle', 'Salesforce', 'ServiceNow'],
    rating: 4.6,
    website: 'https://www.workato.com',
    hasFree: false,
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    category: 'workflow-automation',
    description: 'Developer-focused workflow automation with code-first approach.',
    pricing: '$19/mo',
    pricingTier: 'under-50',
    bestFor: 'Developers building API integrations',
    features: ['Code steps', 'Pre-built triggers', 'SQL support', 'Version control'],
    integrations: ['GitHub', 'Slack', 'Discord', 'Any API'],
    rating: 4.6,
    website: 'https://pipedream.com',
    hasFree: true,
  },

  // CRM Tools
  {
    id: 'hubspot',
    name: 'HubSpot CRM',
    category: 'crm',
    description: 'All-in-one CRM platform with marketing, sales, and service hubs.',
    pricing: '$0/mo',
    pricingTier: 'free',
    bestFor: 'SMBs wanting free CRM with growth path',
    features: ['Contact management', 'Email tracking', 'Pipeline management', 'Reporting'],
    integrations: ['Gmail', 'Outlook', 'Slack', 'Zoom'],
    rating: 4.5,
    website: 'https://www.hubspot.com/products/crm',
    hasFree: true,
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'crm',
    description: 'Enterprise CRM platform with extensive customization and AppExchange.',
    pricing: '$25/mo',
    pricingTier: 'under-50',
    bestFor: 'Large enterprises needing customization',
    features: ['Sales Cloud', 'Einstein AI', 'AppExchange', 'Custom objects'],
    integrations: ['Thousands via AppExchange'],
    rating: 4.4,
    website: 'https://www.salesforce.com',
    hasFree: false,
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    category: 'crm',
    description: 'Sales-focused CRM with visual pipeline and activity-based selling.',
    pricing: '$14/mo',
    pricingTier: 'under-50',
    bestFor: 'Sales teams wanting visual pipeline',
    features: ['Visual pipeline', 'Activity reminders', 'Email integration', 'Reporting'],
    integrations: ['Gmail', 'Outlook', 'Zapier', 'Slack'],
    rating: 4.6,
    website: 'https://www.pipedrive.com',
    hasFree: true,
  },
  {
    id: 'close',
    name: 'Close CRM',
    category: 'crm',
    description: 'CRM built for inside sales teams with built-in calling and SMS.',
    pricing: '$49/mo',
    pricingTier: 'under-50',
    bestFor: 'Inside sales teams doing phone outreach',
    features: ['Built-in calling', 'SMS', 'Email sequences', 'Pipeline view'],
    integrations: ['Zapier', 'Segment', 'Calendly', 'Slack'],
    rating: 4.7,
    website: 'https://www.close.com',
    hasFree: true,
  },
  {
    id: 'monday-crm',
    name: 'Monday Sales CRM',
    category: 'crm',
    description: 'Flexible CRM built on Monday.com with customizable workflows.',
    pricing: '$12/mo',
    pricingTier: 'under-50',
    bestFor: 'Teams already using Monday.com',
    features: ['Custom workflows', 'Email sync', 'Automations', 'Dashboards'],
    integrations: ['Gmail', 'Outlook', 'Slack', 'Zoom'],
    rating: 4.5,
    website: 'https://monday.com/crm',
    hasFree: true,
  },
  {
    id: 'freshsales',
    name: 'Freshsales',
    category: 'crm',
    description: 'AI-powered CRM with built-in phone, email, and chat.',
    pricing: '$15/mo',
    pricingTier: 'under-50',
    bestFor: 'SMBs wanting AI features affordably',
    features: ['Freddy AI', 'Built-in phone', 'Email tracking', 'Territory management'],
    integrations: ['Freshdesk', 'Mailchimp', 'Zapier', 'Slack'],
    rating: 4.5,
    website: 'https://www.freshworks.com/crm/sales/',
    hasFree: true,
  },

  // AI Writing Tools
  {
    id: 'claude',
    name: 'Claude (Anthropic)',
    category: 'ai-writing',
    description: 'Advanced AI assistant for writing, analysis, and coding tasks.',
    pricing: '$20/mo',
    pricingTier: 'under-50',
    bestFor: 'Long-form content and complex analysis',
    features: ['200K context window', 'Document analysis', 'Code generation', 'Artifacts'],
    integrations: ['API access', 'Zapier', 'Make'],
    rating: 4.9,
    website: 'https://claude.ai',
    hasFree: true,
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT (OpenAI)',
    category: 'ai-writing',
    description: 'Versatile AI chatbot for writing, coding, and creative tasks.',
    pricing: '$20/mo',
    pricingTier: 'under-50',
    bestFor: 'General-purpose AI assistance',
    features: ['GPT-4 access', 'DALL-E images', 'Code interpreter', 'Plugins'],
    integrations: ['API access', 'Zapier', 'Make'],
    rating: 4.7,
    website: 'https://chat.openai.com',
    hasFree: true,
  },
  {
    id: 'jasper',
    name: 'Jasper',
    category: 'ai-writing',
    description: 'AI marketing platform for generating brand-consistent content.',
    pricing: '$49/mo',
    pricingTier: 'under-50',
    bestFor: 'Marketing teams needing brand voice',
    features: ['Brand voice', 'Templates', 'Campaign builder', 'Art generation'],
    integrations: ['Google Docs', 'Surfer SEO', 'Grammarly', 'Zapier'],
    rating: 4.5,
    website: 'https://www.jasper.ai',
    hasFree: true,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    category: 'ai-writing',
    description: 'AI copywriting tool with workflows for marketing and sales content.',
    pricing: '$49/mo',
    pricingTier: 'under-50',
    bestFor: 'Sales and marketing copy',
    features: ['90+ templates', 'Workflows', 'Brand voice', 'Infobase'],
    integrations: ['HubSpot', 'Salesforce', 'Zapier'],
    rating: 4.4,
    website: 'https://www.copy.ai',
    hasFree: true,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    category: 'ai-writing',
    description: 'AI writing platform with SEO optimization and factual article generation.',
    pricing: '$19/mo',
    pricingTier: 'under-50',
    bestFor: 'SEO-optimized blog content',
    features: ['Article writer', 'Chatsonic', 'Botsonic', 'SEO optimization'],
    integrations: ['WordPress', 'Surfer SEO', 'Zapier'],
    rating: 4.4,
    website: 'https://writesonic.com',
    hasFree: true,
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    category: 'ai-writing',
    description: 'AI writing assistant for grammar, clarity, and tone improvement.',
    pricing: '$12/mo',
    pricingTier: 'under-50',
    bestFor: 'Polishing and editing written content',
    features: ['Grammar check', 'Tone detection', 'Plagiarism check', 'Style guide'],
    integrations: ['Chrome', 'Word', 'Google Docs', 'Slack'],
    rating: 4.7,
    website: 'https://www.grammarly.com',
    hasFree: true,
  },

  // Sales Intelligence Tools
  {
    id: 'gong',
    name: 'Gong',
    category: 'sales-intelligence',
    description: 'Revenue intelligence platform analyzing sales calls and meetings.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Sales coaching and deal insights',
    features: ['Call recording', 'Deal intelligence', 'Coaching', 'Forecasting'],
    integrations: ['Salesforce', 'HubSpot', 'Zoom', 'Microsoft Teams'],
    rating: 4.7,
    website: 'https://www.gong.io',
    hasFree: false,
  },
  {
    id: 'chorus',
    name: 'Chorus (ZoomInfo)',
    category: 'sales-intelligence',
    description: 'Conversation intelligence for analyzing sales calls and coaching.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Enterprise sales organizations',
    features: ['Call analysis', 'Deal intelligence', 'Onboarding', 'Market intelligence'],
    integrations: ['Salesforce', 'HubSpot', 'Zoom', 'ZoomInfo'],
    rating: 4.5,
    website: 'https://www.chorus.ai',
    hasFree: false,
  },
  {
    id: 'clari',
    name: 'Clari',
    category: 'sales-intelligence',
    description: 'Revenue platform with AI-powered forecasting and pipeline management.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Revenue operations and forecasting',
    features: ['AI forecasting', 'Pipeline inspection', 'Activity capture', 'Mutual action plans'],
    integrations: ['Salesforce', 'HubSpot', 'Gong', 'Outreach'],
    rating: 4.6,
    website: 'https://www.clari.com',
    hasFree: false,
  },
  {
    id: '6sense',
    name: '6sense',
    category: 'sales-intelligence',
    description: 'Account-based marketing platform with AI-powered intent data.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Enterprise ABM programs',
    features: ['Intent data', 'Predictive analytics', 'Account identification', 'Orchestration'],
    integrations: ['Salesforce', 'HubSpot', 'Marketo', 'Outreach'],
    rating: 4.4,
    website: 'https://6sense.com',
    hasFree: false,
  },
  {
    id: 'bombora',
    name: 'Bombora',
    category: 'sales-intelligence',
    description: 'Intent data provider showing which companies are researching topics.',
    pricing: 'Custom',
    pricingTier: '100-plus',
    bestFor: 'Intent-based account prioritization',
    features: ['Company surge data', 'Topic taxonomy', 'Salesforce integration', 'API access'],
    integrations: ['Salesforce', 'HubSpot', 'Marketo', '6sense'],
    rating: 4.3,
    website: 'https://bombora.com',
    hasFree: false,
  },

  // Scheduling Tools
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'scheduling',
    description: 'Scheduling automation platform for booking meetings without back-and-forth.',
    pricing: '$10/mo',
    pricingTier: 'under-50',
    bestFor: 'Individual meeting scheduling',
    features: ['Event types', 'Team scheduling', 'Routing forms', 'Integrations'],
    integrations: ['Google Calendar', 'Outlook', 'Zoom', 'Salesforce'],
    rating: 4.7,
    website: 'https://calendly.com',
    hasFree: true,
  },
  {
    id: 'cal-com',
    name: 'Cal.com',
    category: 'scheduling',
    description: 'Open-source scheduling infrastructure with unlimited bookings.',
    pricing: '$12/mo',
    pricingTier: 'under-50',
    bestFor: 'Teams wanting open-source flexibility',
    features: ['Unlimited bookings', 'Team scheduling', 'Routing', 'Self-hostable'],
    integrations: ['Google Calendar', 'Zoom', 'Stripe', 'Zapier'],
    rating: 4.6,
    website: 'https://cal.com',
    hasFree: true,
  },
  {
    id: 'savvycal',
    name: 'SavvyCal',
    category: 'scheduling',
    description: 'Scheduling tool with personalized links and overlay feature.',
    pricing: '$12/mo',
    pricingTier: 'under-50',
    bestFor: 'Relationship-focused scheduling',
    features: ['Calendar overlay', 'Personalized links', 'Ranked availability', 'Time zone detection'],
    integrations: ['Google Calendar', 'Outlook', 'Zoom', 'Zapier'],
    rating: 4.7,
    website: 'https://savvycal.com',
    hasFree: true,
  },
  {
    id: 'chilipiper',
    name: 'Chili Piper',
    category: 'scheduling',
    description: 'Revenue acceleration platform with instant meeting scheduling.',
    pricing: '$30/mo',
    pricingTier: 'under-50',
    bestFor: 'Inbound lead routing and booking',
    features: ['Instant booking', 'Round robin', 'Handoff', 'Forms integration'],
    integrations: ['Salesforce', 'HubSpot', 'Marketo', 'Calendly'],
    rating: 4.5,
    website: 'https://www.chilipiper.com',
    hasFree: false,
  },

  // Analytics Tools
  {
    id: 'google-analytics',
    name: 'Google Analytics 4',
    category: 'analytics',
    description: 'Free web analytics platform with event-based tracking and AI insights.',
    pricing: '$0/mo',
    pricingTier: 'free',
    bestFor: 'Website traffic and conversion tracking',
    features: ['Event tracking', 'Funnel analysis', 'AI insights', 'BigQuery export'],
    integrations: ['Google Ads', 'Search Console', 'Looker Studio', 'BigQuery'],
    rating: 4.3,
    website: 'https://analytics.google.com',
    hasFree: true,
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    category: 'analytics',
    description: 'Product analytics platform for tracking user behavior and engagement.',
    pricing: '$25/mo',
    pricingTier: 'under-50',
    bestFor: 'Product-led growth companies',
    features: ['Funnel analysis', 'Retention', 'A/B testing', 'User flows'],
    integrations: ['Segment', 'mParticle', 'Zapier', 'Data warehouses'],
    rating: 4.5,
    website: 'https://mixpanel.com',
    hasFree: true,
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    category: 'analytics',
    description: 'Digital analytics platform with behavioral cohorting and experimentation.',
    pricing: '$61/mo',
    pricingTier: '50-100',
    bestFor: 'Enterprise product analytics',
    features: ['Behavioral analytics', 'Experimentation', 'Audiences', 'Data governance'],
    integrations: ['Segment', 'mParticle', 'Snowflake', 'BigQuery'],
    rating: 4.5,
    website: 'https://amplitude.com',
    hasFree: true,
  },
  {
    id: 'hotjar',
    name: 'Hotjar',
    category: 'analytics',
    description: 'Behavior analytics with heatmaps, recordings, and user feedback.',
    pricing: '$32/mo',
    pricingTier: 'under-50',
    bestFor: 'Understanding user behavior visually',
    features: ['Heatmaps', 'Session recordings', 'Surveys', 'Feedback widgets'],
    integrations: ['Google Analytics', 'HubSpot', 'Slack', 'Zapier'],
    rating: 4.4,
    website: 'https://www.hotjar.com',
    hasFree: true,
  },
  {
    id: 'clarity',
    name: 'Microsoft Clarity',
    category: 'analytics',
    description: 'Free behavior analytics with heatmaps and session recordings.',
    pricing: '$0/mo',
    pricingTier: 'free',
    bestFor: 'Free heatmaps and recordings',
    features: ['Heatmaps', 'Session recordings', 'Insights dashboard', 'Copilot AI'],
    integrations: ['Google Analytics', 'Google Tag Manager'],
    rating: 4.6,
    website: 'https://clarity.microsoft.com',
    hasFree: true,
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: 'analytics',
    description: 'Open-source product analytics with feature flags and A/B testing.',
    pricing: '$0/mo',
    pricingTier: 'free',
    bestFor: 'Developers wanting open-source analytics',
    features: ['Product analytics', 'Session replay', 'Feature flags', 'A/B testing'],
    integrations: ['Segment', 'Zapier', 'Slack', 'Data warehouses'],
    rating: 4.6,
    website: 'https://posthog.com',
    hasFree: true,
  },
];

// Helper function to get tools by category
export function getToolsByCategory(categoryId) {
  if (categoryId === 'all') return aiTools;
  return aiTools.filter(tool => tool.category === categoryId);
}

// Helper function to get tools by pricing tier
export function getToolsByPricing(pricingTierId) {
  if (pricingTierId === 'all') return aiTools;
  if (pricingTierId === 'free') return aiTools.filter(tool => tool.hasFree);
  return aiTools.filter(tool => tool.pricingTier === pricingTierId);
}

// Helper function to search tools
export function searchTools(query) {
  const lowercaseQuery = query.toLowerCase();
  return aiTools.filter(tool =>
    tool.name.toLowerCase().includes(lowercaseQuery) ||
    tool.description.toLowerCase().includes(lowercaseQuery) ||
    tool.bestFor.toLowerCase().includes(lowercaseQuery) ||
    tool.features.some(f => f.toLowerCase().includes(lowercaseQuery))
  );
}
